name: Deploy to S3

on:
  push:
    branches:
      - main  # Change this to your main branch name

env:
  CI: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --f

      - name: Build
        run: npm run build


      - name: Deploy to S3
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESSKEY }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_KEY_ACCESS }}
          export AWS_S3_BUCKET=${{ secrets.AWS_S3_BUCKET1 }}
          export AWS_DEFAULT_REGION=us-east-1
          aws s3 sync build s3://$AWS_S3_BUCKET

  
